import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faHome,
    faUser,
    faUserPlus,
    faPlus,
    faTrash,
    faCog,
    faStar,
    faKeyboard,
    faCubes,
    faPaintRoller,
    faTriangleExclamation,
    faImagePortrait,
    faArrowPointer,
    faTags,
    faBookmark,
    faArrowDownUpAcrossLine,
    faListCheck,
    faWindowRestore,
    faPager,
    faDiagramPredecessor,
    faTable,
    faLocationPin, faServer, faDesktop, faImages, faTableCells, faSpinner, faList,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faHome,
    faUser,
    faUserPlus,
    faPlus,
    faTrash,
    faCog,
    faStar,
    faKeyboard,
    faCubes,
    faPaintRoller,
    faTriangleExclamation,
    faImagePortrait,
    faArrowPointer,
    faTags,
    faBookmark,
    faArrowDownUpAcrossLine,
    faListCheck,
    faWindowRestore,
    faPager,
    faDiagramPredecessor,
    faTable,
    faLocationPin,
    faServer,
    faDesktop,
    faImages,
    faTableCells,
    faSpinner,
    faList
);
